### ISSUE TITLE
Unbound module errors

### ISSUE THREAD

**Issue by kuwze** [ocaml/merlin#811] opened 2018-05-01 02:19 UTC
I am trying to use Merlin 3.0.5 on OCaml 4.06.1 and I am getting an error with the [ocaml-tls](https://github.com/mirleft/ocaml-tls) library. I installed ocaml-tls and all of its dependencies, but for some reason I am still getting `Unbound module errors` all the time and I cannot figure out why. Merlin should be using the [.merlin](https://github.com/mirleft/ocaml-tls/blob/master/.merlin) at the root of the project, and when I tried `merlin-use` in Emacs it didn't make any of the errors go away.

Here is a screenshot of my Emacs with the module errors everywhere:
![screenshot from 2018-04-30 22-18-23](https://user-images.githubusercontent.com/31353255/39458687-6f711474-4cc4-11e8-8932-bf8fe5856a4b.png)

**Comment by nilsbecker** [comment] 2018-05-03 13:31
I am having similar problems with merlin 3.0.5 and ocaml 4.06.1. 

in .merlin:

```
PKG csv gsl containers sequence lacaml ctypes
PKG bigarray gen landmarks parmap 
B _build
CMT _build
```

beginning of the source file
```
open Containers
```

upon `:MerlinErrorCheck` i get `Unbound module Containers`. This persists after closing and reopening vim, and after recompiling the source

OS X, ocamlbuild project, MacVim

**Comment by trefis** [comment] 2018-05-14 20:15
Are you sure the merlin you're using is in the same opam switch as the libraries you are trying to use?

**Comment by nilsbecker** [comment] 2018-05-15 09:26
this may have been the problem for me. i cannot reproduce anymore, so consider this fixed (for me at least)

**Closed as completed** 2018-05-15 20:47 UTC
