### ISSUE TITLE
Merlin can't find ppx derivers

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml/merlin#777] opened 2018-01-22 10:08 UTC
Hi,

I am often writing code like 

```ocaml
type t = int [@@deriving yojson, compare, sexp]
```

And while this compiles and works (after adding the necessary `ppx_deriving_yojson`, `ppx_compare` and `ppx_sexp_conv` flags to my jbuild file) Merlin is unable to locate the derivers, it complains about `Cannot locate deriver yojson` (or whatever is first on the line). It doesn't matter which deriver I use (be it `ppx_deriving` based or `type_conv`), it can never find them and consequently it can never type the file.

The relevant line from the build system looks like

```
(preprocess (pps (ppx_deriving_yojson ppx_compare ppx_sexp_conv ppx_driver.runner)))
```

Is there a way I can make it work?

**Comment by tizoc** [comment] 2018-01-24 13:08
I have this problem too (but with `cconv.ppx`), but only when using jbuilder and the `.merlin` file it generates.

I can still build my program using Makefiles + ocamlbuild, and merlin also works fine with the `.merlin` config I had before jbuilder overwrote it.

**Comment by tizoc** [comment] 2018-01-24 16:41
I want to add that I cannot reproduce this issue with `ppx_deriving_yojson`, it works just fine on my computer (both in merlin and when building with jbuilder).

The problems I had with `cconv.ppx` got solvedwith this change https://github.com/c-cube/cconv/pull/13

merlin seems to work as expected, and the issue is in `ppx_driver` and the `ppx_deriving` extensions (or at least that was the case for the problem I was experiencing).

**Comment by sapristi** [comment] 2018-03-17 15:44
Are you guys using opam ? This should solve most of the problems :
https://github.com/ocaml/merlin/wiki/Letting-merlin-locate-go-to-stuff-in-.opam
(also should give a clue to what to do if you are not using opam).

**Comment by rgrinberg** [comment] 2019-12-23 10:13
This should be fixed now. There are some caveats now, but things are mostly working.

**Closed by rgrinberg** 2019-12-23 10:13 UTC
