### ISSUE TITLE
Nice to haves, easy to implement methinks 

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/merlin#448] opened 2015-10-13 20:17 UTC
Small suggestions.

1) Merlin-types buffer should go away when I hit `q`
2) Merlin-types buffer should also know about `merlin-type-enclosing`

**Comment by Fourchaux** [comment] 2015-10-14 12:03
2) : is this not already the case ?

(Merlin_Master)
Currently, the FIRST invocation of 'merlin-type-enclosing' displays the result
in replacement of the original source code. Would be more convenient to have a new window.

**Comment by fxfactorial** [comment] 2015-10-14 15:12
2) No, and I'm using merlin master. I want the type signature as usually in the mini buffer when I check in merlin-types buffer, would rather not have a new buffer.

**Comment by trefis** [comment] 2015-11-06 10:40
1. I agree this is a good idea, why don't you submit a pull request?
2. I don't understand what you mean

**Comment by arichiardi** [comment] 2017-05-05 23:12
@fxfactorial I think I have noticed it depends on the size of the type. It seems like module signatures are actually creating a new buffer. Not sure I have not checked the source code.

**Comment by Khady** [comment] 2017-05-06 02:01
A *merlin-types* buffer is created for all signatures, whatever the size. Which is pretty convenient because I can display it all the time.

**Comment by Wilfred** [comment] 2018-06-30 20:59
I believe 1. is a duplicate of #237.

**Comment by rgrinberg** [comment] 2019-12-23 06:50
I cannot reproduce this using `lsp-mode`. This is the recommended frontend for merlin now.

**Closed by rgrinberg** 2019-12-23 06:50 UTC
Labels: Area/Emacs, Status/0-Triage
