### ISSUE TITLE
Did not manage to find val in class

### ISSUE THREAD

**Issue by objmagic** [ocaml/merlin#720] opened 2017-09-20 04:44 UTC
With OCaml 4.05.0 and Merlin 3.0.2, when I try to go to definition of `a` in method `b`, I got message from Merlin: "didn't manage to find `a`"

```
class a = object
  val mutable a = 1
  method b () =
    if a = 1 then true else false
end
```

**Comment by trefis** [comment] 2018-05-15 23:45
Duplicate of #648.

**Closed by trefis** 2018-05-15 23:45 UTC
Labels: Kind/Bug
