### ISSUE TITLE
Badly resolved ambiguity when a GADT constructor's name match the one of a module. Since OCaml 4.08

### ISSUE THREAD

**Issue by voodoos** [ocaml/merlin#1125] opened 2020-04-08 15:15 UTC
Given the following code:
```ocaml
type _ term =
  | Int : int -> int term
end
```

When asked the type of  `Int` Merlin wrongly answers `(module Stdlib__int)` since OCaml versions >= 4.08.

**Comment by voodoos** [comment] 2020-04-09 12:43
As with previous issues, the enclosing node shows a `core_type` first while `constructor_declaration` was expected.

```
current node is: [[ core_type; constructor_declaration; type_kind; type_declaration; structure_item; structure ]]
```

**Comment by trefis** [comment] 2021-01-06 15:13
Duplicate of #1226.

**Closed** 2021-01-06 15:17 UTC
