### ISSUE TITLE
Problems with MerlinLocate

### ISSUE THREAD

**Issue by ddickstein** [ocaml/merlin#863] opened 2018-09-28 03:27 UTC
I'm having several problems with `:MerlinLocate` which may or may not be related.

Merlin Version: 3.1.0
OCaml Version: 4.07.0
Opam Version: 1.2.2
Operating System: MacOS 10.13.3 (High Sierra)

My project is using dune.

1. `:MerlinLocate` does not work from inside an installed library (i.e. from files in `~/.opam/system/lib`). When I try to use it I just get "Not in environment" errors.
2. When I use `:MerlinLocate` from a file in my project to jump to an installed library, the first time it jumps successfully. However, when I try to jump again, I instead get a message saying, "Several source files in your path have the same name" with a list of possible matches. I think this has something to do with the existence of these files being cached.

**Comment by hanjiexi** [comment] 2018-09-28 19:34
I am having the same issue as @ddickstein. On one of my computers, my Merlin version, OCaml version, and Opam version are the same as his; on another computer, everything is the same except that Opam is on version 2.0.

However, I am using Emacs and VSCode, not Vim, and still experiencing the same issue.

VSCode:
1. In any OCaml file you're working on, right-click a common library function — I chose `Array.concat` — and hit "Go to Definition".
2. It opens `array.ml` from `~/.opam/4.07.0/lib/ocaml` and takes me to line 27
3. Navigate back to the original file and repeat step 1. Result: `No definition found for 'concat'`

Emacs:
1. Open the same file, go to the same function and run C-c C-l
2. It opens line 27 of the same `array.ml` as above in another buffer. Switch back to the original file buffer.
3. Repeat step 1. Result: `"'Array.concat' seems to originate from 'Array' whose ML file could not be found"`

**Comment by hanjiexi** [comment] 2018-10-05 23:49
@ddickstein Can you try again?

Without ever having made any changes/updates to my OCaml install, I am no longer experiencing the issue I described in VSCode or Emacs. So I wonder if this was a system bug fixed by a recent update. I am using Ubuntu 18.04.

**Comment by ddickstein** [comment] 2018-10-06 01:50
Can you clarify what you mean by "system bug fixed by recent update"? Is there a version of Merlin that needs to be updated?

**Comment by hanjiexi** [comment] 2018-10-06 02:55
I mean that an Ubuntu bug may have been the culprit for me because Merlin wasn't working properly on either of my computers (both running Ubuntu 18.04), and then later, without updating any opam packages, suddenly it started working. So you may or may not be right that mine was a different issue.

I don't have a Mac so I can't test if it works there or not. You might want to share more of your system details to help the project maintainer reproduce your problem. As it says in the readme:

> When reporting issues, please include:
> 
>     steps to reproduce the problem, if possible with some code triggering the issue,
>     version of the tools you are using: operating system, editor, OCaml.
> 
> Try to be as specific as possible:
> 
>     avoid generic phrasing such as "doesn't work", explain why it is not working (editor is freezing, you got an error message, the answer is not what was expected, ...)
>     include the content of error messages.
> 
> If it seems relevant, also include information about your development environment:
> 
>     the Opam version and switch in use,
>     other toolchains involved (OCaml flavors, cygwin, C compiler, shell, ...),
>     how the editor was setup.

**Comment by ddickstein** [comment] 2018-10-06 05:09
I provided some system specs at the top - I'm not sure what additional specs would be useful.

**Comment by ddickstein** [comment] 2018-10-08 23:40
@trefis is this something you could take a look at? Is there additional info you need in order to investigate?

**Comment by ddickstein** [comment] 2018-10-08 23:50
Also, I haven't written any `.merlin` files on my own, since I think dune is supposed to take care of that. But I don't know if that applies to external libraries, which may be my trouble (and if this is the issue, where should `.merlin` files be manually added and what should they include)? The external libs do have cmt files.

**Comment by trefis** [comment] 2018-10-09 10:31
There's nothing to be done on merlin's side here: if there are no .merlin when you call locate, then it makes sense that merlin doesn't know where to go.

As for whether .merlin files should be installed alongside libraries (I personally don't think they should), that's another discussion. And a more appropriate place for it would be http://discuss.ocaml.org; it would also be the occasion to discuss why people want to call locate from inside the the install directory.

**Closed by trefis** 2018-10-09 10:31 UTC

**Comment by ddickstein** [comment] 2018-10-09 10:42
Hi @trefis,

There were two issues I was reporting here that I had thought might be related - one of them was that I wasn't able to go to definition from inside the install directory, and the other was that after going to definition once the cached value seemed wrong (either it wasn't able to find the definition again or it found multiple definitions and just reported the file names). I think the latter still needs to be addressed.

Also, if I want to use locate in the install directory, should I add a .merlin file at the root of each library? 

As for why I want this (I'm surprised it's not more widely desired), I often want to understand how/why a library is implementing something, especially when there is a complicated layering of modules (e.g. what you find in core and base). I can move that discussion to http://discuss.ocaml.org as you suggest.

**Comment by trefis** [comment] 2018-10-09 10:47
> and the other was that after going to definition once the cached value seemed wrong (either it wasn't able to find the definition again or it found multiple definitions and just reported the file names). I think the latter still needs to be addressed.

Ah, I had misunderstood that part of your initial message, my bad.

I fixed some things related to that issues a couple of weeks ago, but they weren't released on opam until yesterday (and the version currently on opam is still slightly broken with 4.07.1).
Could you try again, perhaps opam pinning merlin to the git repo? At least until https://github.com/ocaml/opam-repository/pull/12770 is merged.

If that doesn't fix it, please reopen a new issue specific to that problem, it makes it easier for us to track what's going on.
Thank you!
