### ISSUE TITLE
Support OCaml 4.06

### ISSUE THREAD

**Issue by ncihnegn** [ocaml/merlin#748] opened 2017-11-08 16:26 UTC

**Comment by pmetzger** [comment] 2017-11-10 18:56
So why isn't 4.06 supported yet?

**Comment by dbuenzli** [comment] 2017-11-10 19:16
@pmetzger if you follow the project a bit more closely you will see that work for 4.06 is happening in a dedicated branch. However, I don't think the tone of your question is very encouraging for the merlin devs.

**Comment by pmetzger** [comment] 2017-11-11 02:31
It wasn't intended to be mean, my apologies. It was intended to be "what is the technical reason that 4.06 isn't supported, is it another safe string issue or some such?", not "why are you irresponsible bad people not doing this!"

Very sorry if that was misinterpreted. Unfortunately communicating in terse written phrases on the internet makes it difficult to read people's tone. I didn't want to needle anyone. Merlin is a wonderful tool and has made my life better, and I'm very grateful to its creators for the fact that it exists.

**Comment by Fourchaux** [comment] 2017-11-11 12:46
The main technical reason is the writing of the /src/ocaml/typer_406.

**Comment by MarcusE1W** [comment] 2017-11-12 11:22
Is this implemented withy the latest release now? I believe the latest release solved this now 😄

**Comment by let-def** [comment] 2017-11-12 11:39
@pmetzger: no offense taken :), Merlin has a patchset applied on top of ocaml frontend which has to be ported manually. I don't have much time to dedicate to that, so... it is best effort :).

Latest release should solve this problem. While waiting for opam integration, you can try git version with `opam pin add merlin --dev-repo`.
Early feedback is welcome, testing has been quite light :P.

**Comment by vvs-** [comment] 2017-11-12 17:43
The only problem during installation which I've encountered was dependency resolving. I've opened issue opam-repository#10680.

**Closed** 2017-11-13 17:30 UTC
