### ISSUE TITLE
Merlin installation error

### ISSUE THREAD

**Issue by yth** [ocaml/merlin#1231] opened 2021-01-07 14:17 UTC
I am quite new to Ocaml. I am trying to set up an initial development environment. Based on recommendations, I tried to set up merlin using "opam install merlin". I ran into the following error. I have copied the message in its entirety. I am not sure how to parse this and solve it on my own. Any tips or hints would be most welcome.

```
The following actions will be performed:
  ∗ install   dot-merlin-reader 3.4.2 [required by merlin]
  ∗ install   merlin            3.4.2
  ↻ recompile user-setup        0.7   [uses merlin]
===== ∗ 2   ↻ 1 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[dot-merlin-reader.3.4.2] found in cache
[merlin.3.4.2] found in cache
[user-setup.0.7] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of dot-merlin-reader failed at "/home/<user>/.opam/opam-init/hooks/sandbox.sh build dune build -p dot-merlin-reader -j 4".

#=== ERROR while compiling dot-merlin-reader.3.4.2 ============================#
\# context     2.0.5 | linux/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.07.0 | https://opam.ocaml.org/#87778c51
\# path        ~/.opam/4.07.0/.opam-switch/build/dot-merlin-reader.3.4.2
\# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p dot-merlin-reader -j 4
\# exit-code   1
\# env-file    ~/.opam/log/dot-merlin-reader-40061-c743ac.env
\# output-file ~/.opam/log/dot-merlin-reader-40061-c743ac.out
\### output ###
\#     ocamlopt src/ocaml/utils/.utils.objs/native/config.{cmx,o} (exit 2)
\# (cd _build/default && /home/<user>/.opam/4.07.0/bin/ocamlopt.opt -w -40 -g -I src/ocaml/utils/.utils.objs/byte -I src/ocaml/utils/.utils.objs/native -I src/config/.config.objs/byte -I src/config/.config.objs/native -I src/utils/.merlin_utils.objs/byte -I src/utils/.merlin_utils.objs/native -intf-suffix .ml -no-alias-deps -o src/ocaml/utils/.utils.objs/native/config.cmx -c -impl src/ocaml/utils/[...]
\# File "src/ocaml/utils/407_0/config.ml", line 53, characters 16-21:
\# Error: Unbound value srefk
\# Hint: Did you mean s_ref or ref?



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build dot-merlin-reader 3.4.2
└─ 
╶─ No changes have been performed
```

**Comment by trefis** [comment] 2021-01-07 14:25
That looks like a bug on our side indeed, it's the result of a refactoring that wasn't fully tested I guess. I tested with 4.07.1 but not 4.07.0 ... My bad.
I'll see about getting a fix released.

That being said, I'd encourage you to move off of 4.07.0, and onto 4.07.1 (or a more recent version of OCaml).

**Comment by yth** [comment] 2021-01-08 16:22
I had thought it was the latest version available on my platform. However, I just found the other versions through opam. I have upgraded to version 4.11.1. "opam install merlin" worked perfectly with that version. 

I feel comfortable closing this issue since my problem is solved. If you want a reminder to fix the problem for 4.07.0, I can leave the issue open.

If you feel this makes for a good newbie problem and if you can tell me generally where I should look, I am also willing to try to track it down and see where the problem originated and attempt a fix.

**Comment by voodoos** [comment] 2021-04-15 09:37
Duplicate of #1207

**Closed by voodoos** 2021-04-15 09:37 UTC

**Comment by mytran2111** [comment] 2022-01-12 17:28
Hi, I have this error while trying to install merlin using opam install merlin command....

#=== ERROR while compiling cppo.1.6.8 =========================================#
# context     2.1.2 | macos/x86_64 | ocaml-system.4.12.0 | https://opam.ocaml.org#1e60c1ea
# path        ~/.opam/4.12.0/.opam-switch/build/cppo.1.6.8
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cppo -j 7
# exit-code   1
# env-file    ~/.opam/log/cppo-3194-db780e.env
# output-file ~/.opam/log/cppo-3194-db780e.out
### output ###
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:40:2: error: invalid instruction mnemonic 'adrp'
# [...]
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:41:10: error: brackets expression not supported on this target
#  ldr x1, [x1, _camlCppo_version__1@GOTPAGEOFF]
#          ^
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:42:10: error: brackets expression not supported on this target
#  str x1, [x0, #0]
#          ^
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:43:11: error: unknown token in expression
#  movz x0, #1, lsl #0
#           ^
# File "src/cppo_version.ml", line 1:
# Error: Assembler error, input left in file /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build cppo        1.6.8
│ λ build csexp       1.5.1
│ λ build easy-format 1.3.2
│ λ build result      1.5
└─ 
╶─ No changes have been performed
