### ISSUE TITLE
merlin-locate fail to work with module aliasing in LLVM-Ocaml interface

### ISSUE THREAD

**Issue by tddsg** [ocaml/merlin#807] opened 2018-04-22 06:58 UTC
Hi,

I notice that when using the module aliasing feature of OCaml for the Llvm library (installed using `opam`), the feature `merlin-locate` doesn't work properly.

Below is a sample code where I define the alias `module LL = Llvm` and use it to call the function `LL.string_of_llvalue`. When using `merlin-locate` in Emacs, the editor can only jump to the alias definition, but not the definition of the function `string_of_llvalue`

```ocaml
module LL = Llvm
module LS = List

let foo (v: LL.llvalue) =
  let a = LL.string_of_llvalue v in     (* BUG: merlin-locate jumps to line "module LL = Llvm" *)
  let b = Llvm.string_of_llvalue v in   (* OK: merlin-locate jumps to file "llvm.mli" *)
  let c = LS.length [] in               (* OK: merlin-locate jumps to file "list.ml" *)
  ()
```

Here is a part of my `.merlin` file:

```
S ~/.opam/4.06.1/lib
S ~/.opam/4.06.1/lib/*
S ~/.opam/4.06.1/lib/*/*
S ~/.opam/4.06.1/lib/*/*/*
```

Could you double check if this is a bug?

**Comment by trefis** [comment] 2018-05-14 20:16
Where is your cursor when you call `merlin-locate`? On the `string_of_llvalue` part, or on the module part? If the later, then it is not a bug but the expected behavior.

**Comment by tddsg** [comment] 2018-05-16 10:02
The cursor is currently located at the line `module LL = Llvm`.
However, I expect it would open the file `llvm.mli` and would jump to the interface of the function `string_of_llvalue`.

The path to `llvm.mli` is specified by the following two lines in the file `.merlin`

```
S ~/.opam/4.06.1/lib/*
S ~/.opam/4.06.1/lib/*/*
```

**Comment by trefis** [comment] 2018-05-16 13:54
When you call I meant "before the request", not "where do you end up as a result" :)

**Comment by tddsg** [comment] 2018-05-17 02:54
Oh, sorry for the misunderstanding. The cursor was placed in the middle of the string `string_of_llvalue`.

**Comment by trefis** [comment] 2018-05-30 10:13
The behavior you report is surprising, unfortunately I don't have llvm available so I can't really try to reproduce.
But here is some more information you can give me that will probably help understanding what's going on:
- which version of merlin you're using
- a log of what is happening, you can produce one like this:
  + turn logging on with `:MerlinDebugEnable` (vim) or `M-x merlin-enable-debug` (emacs), this should open a buffer in your editor called `:merlin-log:` (vim) or `*merlin-log*` (emacs)
  + try jumping to definition again
  + the log will be in the buffer, it will most like be fairly long, but should contain everything we need for debugging.

PS:
> ```
> S ~/.opam/4.06.1/lib/*
> S ~/.opam/4.06.1/lib/*/*
> ```
You should be doing that, `PKG llvm` should already put all the paths you need in scope. Also, I can't remember if wildcards work.

**Comment by jberdine** [comment] 2018-05-30 11:04
I can repro the behavior reported in the OP. It does not seem to be specific to Llvm though, I see the same for e.g. the Z module from zarith. Extrapolating from just a couple examples (so could easily be wrong), it seems that when merlin-locate cannot find the implementation and falls back to using the interface, then adding a module alias causes the alias to be shown as the source, rather than proceeding through the equation to an interface. In all cases I have tried, if merlin-locate finds an implementation, than adding an alias does not cause trouble.

Tested with merlin 3.0.5 and ocaml 4.06.1

**Comment by tddsg** [comment] 2018-06-05 06:13
@jberdine: Thanks for the comments! I remember having the similar issue with Z3 (from Microsoft) as well.

@trefis I tried the specific path of `llvm` and it still doesn't work.
```
S ~/.opam/4.06.1/lib
S ~/.opam/4.06.1/lib/llvm
```
Here is my OCaml code: https://pastebin.com/Hyr0Vgrf, where I tried to find the definition of the function `LL.fold_left_functions` (line 30).

Here is the link to `*merlin-log*`: https://pastebin.com/cf15JYSu

**Comment by trefis** [comment] 2018-06-05 09:33
Sorry, I miss typed, I meant "you shouldn't* be doing that"!

@jberdine is roughly on the right track, except that it's not "when merlin cannot find the implementation", but "when merlin can find neither of the .cmt or .cmti then ...". Which, looking at the log, is what's happening here.

You might find it a bit sad that merlin decides to stop on the module alias rather than use the information it got from the environment (`llvm.mli, line 1532`) but really, it's the safest choice: the `.mli` might not be in the source path, or there might be more than one in the source path, and we wouldn't know which one to pick (that usually isn't a problem because the `.cmt[i]` gives you the hash of the source file, so you know which one to pick).

To conclude, I don't think this is a bug in merlin: the maintainers of the packages you're having issues with should fix their build system to install `.cmti` files (and perhaps `.cmt`s as well, though that's more questionable).

**Closed by trefis** 2018-06-05 09:33 UTC

**Comment by tddsg** [comment] 2018-06-06 03:04
@trefis : Thank you for the explanation. Yeah, I agree that the packages' maintainers should provide the  `.cmti` files as well.

About the problem that you mentioned: 

> the .mli might not be in the source path, or there might be more than one in the source path, and we wouldn't know which one to pick 

I wonder if it is possible to determine if there is only one `.mli` file in the source path (For some cases, users can configure the file `.merlin` to do so). In this case, it is safe to open that unique `.mli` file. Otherwise, Merlin can throw a warning to report that the `.mli` file is not found, or there are many of them.
