### ISSUE TITLE
Merlin fails to locate identifier that is prefixed with a bang (!) character

### ISSUE THREAD

**Issue by matejkosik** [ocaml/merlin#797] opened 2018-03-22 14:52 UTC
I have noticed that in a code like this:
```Ocaml
let incr (i : int ref) : unit =
  i := succ !i
```
Merlin, in the function body, is able to find the location of the first `i`, but it fails to find the location of the second `i`.

However, all is well if I rewrite the function like this:
```Ocaml
let incr (i : int ref) : unit =
  i := succ !(i)
```

I guess that Merlin should be able to cope also with the first (shorter / nicer) of the function.
What do you think?

**Comment by trefis** [comment] 2018-03-22 16:50
This is a duplicate of #624 and #652 .
Haven't add time to look into it yet.

Btw, in the future, please do share the result of merlin instead of just saying "it fails". Thanks :)

**Closed by trefis** 2018-03-22 16:50 UTC
