### ISSUE TITLE
FLG/ppx handling seems to be broken with jbuilder

### ISSUE THREAD

**Issue by hcarty** [ocaml/merlin#678] opened 2017-07-21 20:59 UTC
Using Lwt 3.1.0's recent release, jbuilder produces the following FLG line:
```
FLG -ppx "../_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx --cookie 'library-name="mylib"'"
```
which causes at least the vim mode for merlin to choke and fail.  The error seems to be:
```
merlin.Error: {u'message': u"Error while running external preprocessor\nCommand line: ../_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx --cookie 'library-name=mylib' '/tmp/camlppxb1b38e' '/tmp/camlppxdb29d9' 1>/dev/null 2>/dev/null", u'valid': True, u'type': u'type', u'sub': []}
```
This is using merlin 2.5.5 and jbuilder 1.0+beta10.

@diml as I'm not sure if this is a merlin or jbuilder issue

**Comment by diml** [comment] 2017-07-24 10:43
Not sure, @let-def can we quote stuff in .merlin files?

**Comment by let-def** [comment] 2017-07-24 10:52
Yes, merlin tries to follow shell splitting conventions. I will try to reproduce that, @hcarty can you share the code?

**Comment by let-def** [comment] 2017-07-24 11:09
(by the way, jbuilder quoting should be `\"mylib\"`, but unless there are spaces in mylib it should not matter)

**Comment by samoht** [comment] 2017-07-24 12:35
I have the same issue. For instance, try to build https://github.com/mirage/ocaml-dns-forward/pull/70

**Comment by diml** [comment] 2017-07-24 12:44
@let-def how are the arguments of `FLG` read?

Currently jbuilder quote individual argument of the ppx using `Filename.quote` and just surround the final command string with double quotes. If I use `Filename.quote` instead of the full command string, I get:

```
FLG - ppx '../_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx --cookie '\''library-name="mylib"'\'''
```

is that acceptable?

**Comment by let-def** [comment] 2017-07-24 14:21
I see. Merlin 3.0.0 is processing attributes correctly but right now on opam, it is Merlin 2.5.5 which fails with FLG -ppx.

**Comment by let-def** [comment] 2017-07-24 14:23
@diml Yes, this quoting should be fine.

**Comment by diml** [comment] 2017-07-24 14:33
I changed the quoting in janestreet/jbuilder@6e48e70a74616f34e54a21926d57a42b09832b26

**Comment by hcarty** [comment] 2017-07-24 20:09
Still seems broken with merlin's latest master and jbuilder's latest master.

**Comment by hcarty** [comment] 2017-07-24 20:17
Example: https://github.com/hcarty/jbuild-merlin-example

```
git clone https://github.com/hcarty/jbuild-merlin-example.git
cd jbuild-merlin-example
jbuilder build --dev
vim src/m.ml
# Lwt syntax doesn't work in the editor but the code builds just fine
```
Needs Lwt 3.1.0.

**Comment by hcarty** [comment] 2017-07-24 20:17
Testing with jbuilder#master and merlin#master as of a few minutes ago.

**Comment by diml** [comment] 2017-07-25 12:27
@hcarty can you try with [this PR](https://github.com/janestreet/jbuilder/pull/201)?

**Comment by hcarty** [comment] 2017-07-25 18:18
@diml Same issue with the jbuild-merlin-example project I linked to using merlin 3.0.0 and jbuilder pinned to PR#201.  merlin reports `%lwt` as an uninterpreted extension.

**Comment by hcarty** [comment] 2017-07-25 18:20
.merlin is now:
```
B ../_build/default/src
FLG -ppx '/home/hcarty/jbuild-merlin-example/_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx --cookie '\''library-name="m"'\'''
FLG -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs
PKG bigarray
PKG bytes
PKG lwt
PKG lwt.log
PKG lwt.unix
PKG result
PKG unix
```

**Comment by diml** [comment] 2017-07-26 09:01
@hcarty can you get a debug log from merlin?

**Comment by hcarty** [comment] 2017-07-26 16:41
@diml How do I get merlin to output a debug log?  I thought setting the `MERLIN_DEBUG=/tmp/merlin.log` environment variable would work but it doesn't seem to have any effect.  `:let g:merlin_debug=1` from vim doesn't seem to do much either.

**Comment by hcarty** [comment] 2017-07-26 16:45
Apologies - I missed the special buffer created in vim.

@diml here is the log - https://gist.github.com/hcarty/c52f07d1e04f02f56209801c911a459f

**Comment by diml** [comment] 2017-07-26 16:50
This is the relevant part of the log:

```
# 0.52 Mppx - rewrite
failed with Error while running external preprocessor
Command line: /home/hcarty/projects/upstream/jbuild-merlin-example/_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx --cookie 'library-name="m"' '/tmp/camlppxd65fb3' '/tmp/camlppx67b4c8' 1>/dev/null 2>/dev/null
```

Maybe you can try to run this command by hand. You can drop the `--as-ppx` and replace the last two `/tmp/camlpp...` by just the .ml file

**Comment by hcarty** [comment] 2017-07-26 18:51
With `--as-ppx`
```
$ /home/hcarty/projects/upstream/jbuild-merlin-example/_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx --cookie 'library-name="m"' src/m.ml
ppx.exe: unknown option '--cookie'.
ppx.exe [options] <input ast file> <output ast file>
  -no-debug disable debug mode
  -log enable logging
  -no-log disable logging
  -no-sequence disable sequence operator
  -no-strict-sequence allow non-unit sequence operations
  -help  Display this list of options
  --help  Display this list of options
```
Without `--as-ppx`
```
$ /home/hcarty/projects/upstream/jbuild-merlin-example/_build/default/.ppx/lwt.ppx/ppx.exe --cookie 'library-name="m"' src/m.ml
let f x =
  Lwt.try_bind (fun ()  -> x ())
    (function | None  -> Lwt.return_true | Some _ -> Lwt.return_false)
    (function | exn -> Lwt.fail exn)
```

**Comment by diml** [comment] 2017-07-27 09:03
If you pass `--as-ppx` you need to pass two filenames as last arguments, i'm not sure what's the behavior if you don't. The two filenames are the input and output

**Comment by hcarty** [comment] 2017-07-27 14:02
@diml Still the same output, even with two files passed in:
```
$ /home/hcarty/projects/upstream/jbuild-merlin-example/_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx --cookie 'library-name="m"' /home/hcarty/projects/upstream/jbuild-merlin-example/src/m.ml /tmp/out.ml
ppx.exe: unknown option '--cookie'.
ppx.exe [options] <input ast file> <output ast file>
  -no-debug disable debug mode
  -log enable logging
  -no-log disable logging
  -no-sequence disable sequence operator
  -no-strict-sequence allow non-unit sequence operations
  -help  Display this list of options
  --help  Display this list of options
```

**Comment by hcarty** [comment] 2017-07-27 14:03
Ah, but `m.ml` is OCaml, not serialized AST.  Is that the issue with how I'm running the `--as-ppx` version?

**Comment by hcarty** [comment] 2017-07-27 21:47
If I edit the ppx `FLG` line to the following everything works until I `jbuilder build --dev` again and the `.merlin` gets overwritten:
```
FLG -ppx '/home/hcarty/projects/upstream/jbuild-merlin-example/_build/default/.ppx/lwt.ppx/ppx.exe --as-ppx'
```

**Comment by diml** [comment] 2017-07-28 07:37
> Ah, but m.ml is OCaml, not serialized AST. Is that the issue with how I'm running the --as-ppx version?

This would be an issue, but it's failing while parsing the command line, so before loading the file.

This seems to be an issue with the ocaml-migrate-parsetree driver, what version of omp are you using?

**Comment by diml** [comment] 2017-07-28 10:47
I just checked, `--cookie` was ignored when `--as-ppx` was passed, it's fixed in the master of omp

**Comment by hcarty** [comment] 2017-07-28 16:58
@diml Thank you for all your help troubleshooting!  With jbuilder and omp pinned to master it works.  I haven't tried with the released version of jbuilder.

I think that this can be closed now.

**Closed** 2017-07-28 16:58 UTC
