### ISSUE TITLE
'merlin-locate' - "Not a valid identifier" message

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/merlin#652] opened 2017-05-17 12:53 UTC
Merlin-master, OCaml 4.03.0 (4.04.1 | 4.05.0)+flambda , Spacemacs

  With the following examples, a 'merlin-locate' pointing on the 2nd 'x'
prints the message "Not a valid identifier" :

```ocaml
fun x -> [x] ;;
fun x -> {x} ;;
fun x -> [|x|] ;;
fun x -> {|x|} ;;
fun x -> {<x>} ;;
fun x -> ~x ;;

(*Also: *)
fun a x -> (a,x) ;;
```
 
Examples without problem :
```ocaml
fun x -> [ x] ;; (* OK : Use C-c & to go back. *)
fun x -> { x} ;;
fun x -> [| x|] ;;
fun a x -> (a, x) ;;

(* Also OK : *)
fun x -> (x) ;;

```

**Comment by trefis** [comment] 2017-07-04 10:43
Seems to be the same issue as #624 .

**Comment by Fourchaux** [comment] 2018-02-18 17:38
Merlin-master, OCaml 4.06.1+rc1, Emacs

Another 1-character miss with merlin-locate:
```ocaml
let cong x xs = x::xs
```
Cursor just after :: (on l) + merlin-locate -> "Not a valid identifier"

Cursor 2 characters after :: (on s) + merlin-locate -> OK

**Comment by trefis** [comment] 2018-03-22 16:53
Closing as this is indeed a duplicate of #624 .
No one has had time to look at this yet, sorry for the annoyance.

Feel free to ping #624 again in a few weeks if it hasn't been resolved by then.

**Closed by trefis** 2018-03-22 16:53 UTC
Labels: Kind/Bug
