### ISSUE TITLE
Go to definition is confused by module signatures

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/merlin#415] opened 2015-07-09 22:48 UTC
``` ocaml
module type S = sig
  val x : int
end

module A : S = struct
  let x = 123
end

let _ = A.x (* <- cursor on the x *)
```

In this snippet, try to go to definition of `A.x` and merlin will jump `val x` in the signature rather than the definition itself. I'd expect it to go to the actual definition of `x` inside `A`.

**Comment by trefis** [comment] 2015-07-09 22:55
This is the expected behavior.
I'm not saying it's the right one in this particular case, but I believe
it's the preferred option in general:

- when the definition is in another module, you want to go to the MLI, not
the ml.
- when you have [module M : sig val x : int end = struct let x = 42 end],
you want to go to the signature

Now indeed maybe in your case you want to go to the implementation and not
the interface. Maybe.
I think that rather than adding more particular cases in an already
dreadful piece of code, what you want is have a good way to retrieve
documentation without locating, and tell merlin to always locate the
implementation, never the interface.
(The assumption here being that people use locate as a poor way to retrieve
documentation)

What do you think?

Le ven. 10 juil. 2015 00:48, Rudi Grinberg <notifications@github.com> a
écrit :

**Comment by rgrinberg** [comment] 2015-07-09 23:05
I can see how going to the interface is useful a lot of the time but in my case I definitely want the implementation. My concrete use case is when working on the uri library. Particularly this bit:

https://github.com/mirage/ocaml-uri/blob/master/lib/uri.ml#L70

Going to the module type isn't very useful to me in this case and I'd much rather go to the implementation directly.

IMO both behaviors are useful and I'd like to be able to just pick the one I'd like rather than have merlin decide.

**Comment by dbuenzli** [comment] 2015-07-09 23:20
> In this snippet, try to go to definition of A.x and merlin will jump val x in the signature rather than the definition itself. I'd expect it to go to the actual definition of x inside A.

For emacs this is related to #308 and #294. I tend to see this as natural aswell however a further locate when on S.x should then maybe jump on the def of `A`. In this case it makes the operation slightly modal in the sense that we need to remember where we started from, but it's very natural if you think about the `S` being inlined at its definition point.  To be more precise I think that when you try to locate a located identifier it should switch between its implementation and its interface. 

Now maybe what trefis suggests about doc is right and then one way of making the interaction modeless would be to always jump to the implementation and then if a locate is performed on the identifier there it jumps on to its interface definition (if any). Going back from there to the implementation can be handled by an editor mark mechanism (see #294) rather than merlin itself so that it doesn't have to remember where it came from (since there could be more than one implementation point to refer to).

**Comment by dbuenzli** [comment] 2015-07-09 23:24
Also always going to implementation first makes the operation more predictable to the user.

**Comment by rgrinberg** [comment] 2015-07-10 00:28
I see. So I guess this is a duplicate. @trefis feel free to close.

@dbuenzli IMO the user should just be able to choose between going to the implementation or the interface. Something like your toggling behavior should be left to the editors to implement.

**Comment by dbuenzli** [comment] 2015-07-10 00:53
> @dbuenzli IMO the user should just be able to choose between going to the implementation or the interface. 

Too many commands, my brain is small. Besides I'm sure the time you take to actually think about which one you want at a given instant is longer that issuing the command once and a second time once you realize you are in the implementation and want the interface. I prefer to have a single command that allows me to navigate the whole space in a very deterministic manner (which implies always implementation first).


> Something like your toggling behavior should be left to the editors to implement.

Implementing going from an implementation to its signature definition (if any) needs the kind of OCaml knowledge merlin has and cannot be left to the editor. Forward navigation needs to be implemented by merlin, however going *back* in the navigation procedure can be left to the editor.

**Comment by rgrinberg** [comment] 2015-07-10 00:57
> Implementing going from an implementation to its signature definition (if any) needs the kind of OCaml knowledge merlin has and cannot be left to the editor

I was thinking of something simple like merlin returning a list of locations and labeling what kind of location is it. The editor simply shuffles between them.

Thinking about this a little more. I'd really just prefer to name these commands differently:

* Go to definition. Always prefer the implementation
* Go to documentation. Always prefer the interface.

**Comment by struktured** [comment] 2015-07-10 01:47
:+1:  for finding and appropriately labeling all choices when ambiguities arise. Ran into the same exact problem this week.

I also have a very similar issue when multiple modules exist of the same name (in different folders). I'm moving away from this naming convention because merlin tends to pick the wrong one and emit syntax errors, which then causes the go to definition functionality to choose wrong as well. If merlin is unsure, just show me both in a menu.

**Comment by trefis** [comment] 2015-07-10 09:29
> IMO the user should just be able to choose between going to the implementation or the interface. Something like your toggling behavior should be left to the editors to implement.

This is already the case, and has been for a year.
In vim: `let g:merlin_locate_preference = 'ml'/'mli'`.

There is something similar in emacs.

> Go to documentation. Always prefer the interface.

See `:MerlinDocument`

**Comment by trefis** [comment] 2015-07-10 14:29
> merlin tends to pick the wrong one and emit syntax errors, which then causes the go to definition functionality to choose wrong as well

I didn't understand that part.

> If merlin is unsure, just show me both in a menu.

That's what it does (excepts it shows you an error message, not a menu, maybe that would be better).
If merlin brings you somewhere, it is *sure*. It may be wrong, it may not be what you expected, but it is the only option which made sense.

**Comment by struktured** [comment] 2015-07-11 05:21
By "tends to pick the wrong one", I mean it chooses the wrong file definition when multiple ones create the same module name in the same project. In particular, ```.merlin``` is defined in folder ```project```. There are files ```project/src/foo/impl.ml```, ```project/src/foo/util.ml```, and ```project/src/bar/impl.ml```. The ```.merlin``` file has ```S src/**``` and a build entry for where ocamlbuild puts things.

In ```foo/util.ml```, if I refer to module ```Impl.M``` that is defined in both ```foo/impl.ml``` and ```bar/impl.ml```, merlin deduces the one from ```bar/impl.ml``` even though ```foo/impl.ml``` is the only one which would make the code compile properly.

**Comment by def-lkb** [comment] 2015-07-13 12:35
@struktured: I would advise against having multiple modules with the same name covered by the same .merlin file. You might get the right module selected by chance, but that's not reliable (in the current case, I suspect it works only because "." has precedence over other paths discovered in the .merlin file).

What about:
project/.merlin: main project .merlin file, with globally visible informations
project/src/foo/.merlin project/src/bar/.merlin: foo and bar specific definitions. Add one line with the `REC` directive to recurse in parent directories and load "project/.merlin" file. Local definitions will have precedence over one from the parent file.

**Comment by def-lkb** [comment] 2015-07-13 12:36
(this is just a general concern, outside of any "locate" functionality consideration, lookup logic for CMT files is slightly different)

**Comment by dbuenzli** [comment] 2015-07-13 13:20
> I would advise against having multiple modules with the same name covered by the same .merlin file.

I don't think this assumption can be fulfilled in practice, especially when you are dealing with libraries that define different libraries to target multiple backends (e.g. js vs unix). So it would be nice if merlin had a clear story about that so that it makes its behaviour well understood in these cases.

In practice an UI could be put on top of that for when an ambiguity arises: present the ambiguous destinations, provide the ability to select one and (by default) validate it as the destination for the session (defaults could also be cast in stone in the .merlin file in case you always know which destination will be used in practice).

> What about:
[...]

Pooping `.merlin` files in the whole source hierarchy makes things less understandable when they are problems and harder to maintain than it should be. I'd prefer if one could centralize the definitions in a root .merlin file (if only to make it easy to [generate](https://github.com/samoht/assemblage/blob/c0eb32a008a29b68d0dbd84858d918190c67a6f4/lib-driver/ast_merlin.ml)). Besides I think that using the file system as a sort of namespacing/information hiding structure may not be the best idea (yes I know most compilers actually do that). 

FWIW in assemblage we are moving away from the "your build directory" is a "mirror of your source tree" model; to make builds more isolated and to make it easier to mix and match sources into coherent libraries, which will make these kind of ambiguity problems even more acute.

**Comment by def-lkb** [comment] 2015-07-13 15:41
The problem can be formulated as follow: merlin as to find which set of flags was passed / would be passed to the compiler to compile a given file.
There are contextual issues: a given file might be interpreted differently in different contexts (maybe what you try to solve by having multiple build directories.
Also observe the control flow is reversed: while the build system is asked to build a target and then invokes the compiler with specific files and settings, merlin is given a file and has to figure out the relevant subset of the build environment.

Given this set of constraint, all we have to find is a simple, declarative (non-turing complete) way to specify that.

> I don't think this assumption can be fulfilled in practice, especially when you are dealing with libraries that define different libraries to target multiple backends (e.g. js vs unix). So it would be nice if merlin had a clear story about that so that it makes its behaviour well understood in these cases.

Do you mean your code can be compiled against different packages providing a module with the same name? Then merlin should see the same package as the one used for compiling cmi files.
Or that you have multiple b.ml, used by a single a.ml?

**Comment by dbuenzli** [comment] 2015-07-13 16:19
> Also observe the control flow is reversed: while the build system is asked to build a target and then invokes the compiler with specific files and settings, merlin is given a file and has to figure out the relevant subset of the build environment.

I think the data structures in assemblage should be able to give you back that mapping. However the problem here is that in assemblage the mapping from source to build products is not one-to-one as sources can be mixed-and-matched into [parts](http://samoht.github.io/assemblage/Assemblage.Part.html)) for building. 

Basically a part corresponds to a library, an executable, etc. and each will have their own build dirs in which the sources are copied (`ln`d to be precise) and the same source can be used in different parts. So in such a system you would like to be able to define named contexts that precisely define how a source is being used (in an assemblage settings the names here would match those of the part). If when you try to ask merlin something about a file it's being used in more than one context, the tool should prompt you in which context you'd like the source to be interpreted.

> Given this set of constraint, all we have to find is a simple, declarative (non-turing complete) way to specify that.

I'm not sure I really understood what *that* is, is it simply the list of packages and project local files one source can see while it's being compiled ? 

> Do you mean your code can be compiled against different packages providing a module with the same name? Then merlin should see the same package as the one used for compiling cmi files.
> Or that you have multiple b.ml, used by a single a.ml?

I mean that these duplicates do not necessarily interact together in the build procedure, but they do exist with duplicate names in the same source hierarchy. See for example the files in the `src-*` directories in  https://github.com/dbuenzli/jsont

**Comment by voodoos** [comment] 2022-07-27 08:29
This is fixed on master: Merlin now provides both "jump to declaration" and "jump to definition" and both work as expected in the first post's example.

**Closed by voodoos** 2022-07-27 08:29 UTC
Labels: Kind/Bug
